In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv('pre_race.csv', index_col=0)
df

,meeting_name,year,location,avg_track_temperature,avg_wind_speed,historical_sc_prob,historical_rain_prob,track_length,n_of_corners,degradation,...,dist_soft,starting_compound,tyre_age_at_start,first_stint_length,avg_hard_stint_by_race,avg_med_stint_by_race,avg_soft_stint_by_race,avg_hard_stint_by_driver,avg_med_stint_by_driver,avg_soft_stint_by_driver
0,Bahrain Grand Prix,2024,Sakhir,22.81,0.55,0.67,0.00,5412,15,Very-High,...,0.96,SOFT,3.0,17.0,15.0,15.0,12.0,NaN,NaN,14.0
1,Bahrain Grand Prix,2023,Sakhir,29.90,0.49,0.67,0.00,5412,15,Very-High,...,0.96,SOFT,3.0,14.0,15.0,15.0,12.0,NaN,NaN,14.0
2,Bahrain Grand Prix,2023,Sakhir,29.90,0.49,0.67,0.00,5412,15,Very-High,...,0.83,SOFT,0.0,12.0,15.0,15.0,12.0,NaN,NaN,11.0
3,Bahrain Grand Prix,2023,Sakhir,29.90,0.49,0.67,0.00,5412,15,Very-High,...,0.89,SOFT,0.0,10.0,15.0,15.0,12.0,NaN,NaN,11.0
4,Bahrain Grand Prix,2023,Sakhir,29.90,0.49,0.67,0.00,5412,15,Very-High,...,0.83,SOFT,0.0,9.0,15.0,15.0,12.0,NaN,NaN,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1729,Abu Dhabi Grand Prix,2025,Yas Island,30.24,1.65,0.33,0.00,5281,16,Medium-Low,...,0.00,MEDIUM,0.0,14.0,32.0,16.0,8.0,NaN,18.0,NaN
1730,Abu Dhabi Grand Prix,2025,Yas Island,30.24,1.65,0.33,0.00,5281,16,Medium-Low,...,0.00,HARD,0.0,41.0,32.0,16.0,8.0,41.0,8.0,NaN
1731,Abu Dhabi Grand Prix,2025,Yas Island,30.24,1.65,0.33,0.00,5281,16,Medium-Low,...,0.00,MEDIUM,0.0,14.0,32.0,16.0,8.0,NaN,14.0,NaN
1732,Spanish Grand Prix,2025,Barcelona,48.12,1.82,0.33,0.33,4657,14,High,...,0.94,NaN,NaN,NaN,16.0,19.0,15.0,NaN,NaN,16.0
1733,Singapore Grand Prix,2023,Marina Bay,35.83,1.61,0.33,0.00,4940,19,Medium,...,0.29,NaN,NaN,NaN,34.0,26.0,18.0,26.0,NaN,38.0

In [10]:
df3 = df[(df['meeting_name'] == 'Monaco Grand Prix') & (df['full_name'] == 'Max VERSTAPPEN')]
df3

,meeting_name,year,location,avg_track_temperature,avg_wind_speed,historical_sc_prob,historical_rain_prob,track_length,n_of_corners,degradation,...,dist_soft,starting_compound,tyre_age_at_start,first_stint_length,avg_hard_stint_by_race,avg_med_stint_by_race,avg_soft_stint_by_race,avg_hard_stint_by_driver,avg_med_stint_by_driver,avg_soft_stint_by_driver
117,Monaco Grand Prix,2023,Monaco,36.02,1.12,0.33,0.33,3337,19,Very-Low,...,0.0,MEDIUM,0.0,55.0,28.0,17.0,0.0,14.0,55.0,NaN
733,Monaco Grand Prix,2024,Monaco,44.47,0.95,0.33,0.33,3337,19,Very-Low,...,0.0,HARD,0.0,1.0,28.0,17.0,0.0,14.0,55.0,NaN
1333,Monaco Grand Prix,2025,Monaco,43.15,0.92,0.33,0.33,3337,19,Very-Low,...,0.0,HARD,0.0,27.0,28.0,17.0,0.0,14.0,55.0,NaN

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1734 entries, 0 to 1733
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   meeting_name              1734 non-null   object
 1   year                      1734 non-null   int64
 2   location                  1734 non-null   object
 3   avg_track_temperature     1734 non-null   float64
 4   avg_wind_speed            1734 non-null   float64
 5   historical_sc_prob        1734 non-null   float64
 6   historical_rain_prob      1734 non-null   float64
 7   track_length              1734 non-null   int64
 8   n_of_corners              1734 non-null   int64
 9   degradation               1734 non-null   object
 10  overtake_difficulty       1734 non-null   object
 11  avg_pit_time              1734 non-null   float64
 12  tipical_n_of_pitstops     1734 non-null   int64
 13  driver_number             1734 non-null   int64
 14  full_name                 1734 non-null   object
 15  team_name                 1734 non-null   object
 16  driver_baseline_pace      1728 non-null   float64
 17  grid_position             1734 non-null   int64
 18  grid_category             1734 non-null   object
 19  dist_hard                 1734 non-null   float64
 20  dist_medium               1734 non-null   float64
 21  dist_soft                 1734 non-null   float64
 22  starting_compound         1732 non-null   object
 23  tyre_age_at_start         1732 non-null   float64
 24  first_stint_length        1698 non-null   float64
 25  avg_hard_stint_by_race    1734 non-null   float64
 26  avg_med_stint_by_race     1734 non-null   float64
 27  avg_soft_stint_by_race    1616 non-null   float64
 28  avg_hard_stint_by_driver  448 non-null    float64
 29  avg_med_stint_by_driver   1393 non-null   float64
 30  avg_soft_stint_by_driver  561 non-null    float64
dtypes: float64(17), int64(6), object(8)
memory usage: 433.5+ KB

In [3]:
df['meeting_name'].unique()

array(['Bahrain Grand Prix', 'Saudi Arabian Grand Prix',
       'Australian Grand Prix', 'Azerbaijan Grand Prix',
       'Miami Grand Prix', 'Monaco Grand Prix', 'Spanish Grand Prix',
       'Canadian Grand Prix', 'Austrian Grand Prix', 'British Grand Prix',
       'Hungarian Grand Prix', 'Belgian Grand Prix', 'Dutch Grand Prix',
       'Italian Grand Prix', 'Singapore Grand Prix',
       'Japanese Grand Prix', 'Qatar Grand Prix',
       'United States Grand Prix', 'Mexico City Grand Prix',
       'São Paulo Grand Prix', 'Las Vegas Grand Prix',
       'Abu Dhabi Grand Prix', 'Chinese Grand Prix',
       'Emilia Romagna Grand Prix'], dtype=object)

In [20]:
race_list = ['Bahrain Grand Prix', 'Saudi Arabian Grand Prix',
       'Australian Grand Prix', 'Azerbaijan Grand Prix',
       'Miami Grand Prix', 'Monaco Grand Prix', 'Spanish Grand Prix',
       'Canadian Grand Prix', 'Austrian Grand Prix', 'British Grand Prix',
       'Hungarian Grand Prix', 'Belgian Grand Prix', 'Dutch Grand Prix',
       'Italian Grand Prix', 'Singapore Grand Prix',
       'Japanese Grand Prix', 'Qatar Grand Prix',
       'United States Grand Prix', 'Mexico City Grand Prix',
       'São Paulo Grand Prix', 'Las Vegas Grand Prix',
       'Abu Dhabi Grand Prix', 'Chinese Grand Prix',
       'Emilia Romagna Grand Prix']

columns = ['avg_soft_stint_by_race', 'avg_hard_stint_by_driver', 'avg_med_stint_by_driver', 'avg_soft_stint_by_driver']

# where a certain driver is missing pace data on certain compounds it will be populated by the mean value of the pace performed on that specific race
for race in race_list:
    mask = df['meeting_name'] == race
    for col in columns:
        df.loc[mask, col] = df.loc[mask, col].fillna(df.loc[mask, col].mean())

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1734 entries, 0 to 1733
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   meeting_name              1734 non-null   object
 1   year                      1734 non-null   int64
 2   location                  1734 non-null   object
 3   avg_track_temperature     1734 non-null   float64
 4   avg_wind_speed            1734 non-null   float64
 5   historical_sc_prob        1734 non-null   float64
 6   historical_rain_prob      1734 non-null   float64
 7   track_length              1734 non-null   int64
 8   n_of_corners              1734 non-null   int64
 9   degradation               1734 non-null   object
 10  overtake_difficulty       1734 non-null   object
 11  avg_pit_time              1734 non-null   float64
 12  tipical_n_of_pitstops     1734 non-null   int64
 13  driver_number             1734 non-null   int64
 14  full_name                 1734 non-null   object
 15  team_name                 1734 non-null   object
 16  driver_baseline_pace      1728 non-null   float64
 17  grid_position             1734 non-null   int64
 18  grid_category             1734 non-null   object
 19  dist_hard                 1734 non-null   float64
 20  dist_medium               1734 non-null   float64
 21  dist_soft                 1734 non-null   float64
 22  starting_compound         1732 non-null   object
 23  tyre_age_at_start         1732 non-null   float64
 24  first_stint_length        1698 non-null   float64
 25  avg_hard_stint_by_race    1734 non-null   float64
 26  avg_med_stint_by_race     1734 non-null   float64
 27  avg_soft_stint_by_race    1656 non-null   float64
 28  avg_hard_stint_by_driver  1734 non-null   float64
 29  avg_med_stint_by_driver   1734 non-null   float64
 30  avg_soft_stint_by_driver  1656 non-null   float64
dtypes: float64(17), int64(6), object(8)
memory usage: 433.5+ KB

In [21]:
# Since there are still Nan values in column 'avg_soft_stint_by_race' and 'avg_soft_stint_by_driver'
# This will be populated with overall average values, which is a bit distorting but at least it won't crash the program

df['avg_soft_stint_by_race'] = df['avg_soft_stint_by_race'].fillna(df['avg_soft_stint_by_race'].mean())
df['avg_soft_stint_by_driver'] = df['avg_soft_stint_by_driver'].fillna(df['avg_soft_stint_by_driver'].mean())

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1734 entries, 0 to 1733
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   meeting_name              1734 non-null   object
 1   year                      1734 non-null   int64
 2   location                  1734 non-null   object
 3   avg_track_temperature     1734 non-null   float64
 4   avg_wind_speed            1734 non-null   float64
 5   historical_sc_prob        1734 non-null   float64
 6   historical_rain_prob      1734 non-null   float64
 7   track_length              1734 non-null   int64
 8   n_of_corners              1734 non-null   int64
 9   degradation               1734 non-null   object
 10  overtake_difficulty       1734 non-null   object
 11  avg_pit_time              1734 non-null   float64
 12  tipical_n_of_pitstops     1734 non-null   int64
 13  driver_number             1734 non-null   int64
 14  full_name                 1734 non-null   object
 15  team_name                 1734 non-null   object
 16  driver_baseline_pace      1728 non-null   float64
 17  grid_position             1734 non-null   int64
 18  grid_category             1734 non-null   object
 19  dist_hard                 1734 non-null   float64
 20  dist_medium               1734 non-null   float64
 21  dist_soft                 1734 non-null   float64
 22  starting_compound         1732 non-null   object
 23  tyre_age_at_start         1732 non-null   float64
 24  first_stint_length        1698 non-null   float64
 25  avg_hard_stint_by_race    1734 non-null   float64
 26  avg_med_stint_by_race     1734 non-null   float64
 27  avg_soft_stint_by_race    1734 non-null   float64
 28  avg_hard_stint_by_driver  1734 non-null   float64
 29  avg_med_stint_by_driver   1734 non-null   float64
 30  avg_soft_stint_by_driver  1734 non-null   float64
dtypes: float64(17), int64(6), object(8)
memory usage: 433.5+ KB

In [47]:
dasdas = df[(df['meeting_name'] == 'Bahrain Grand Prix') & (df['driver_number'] == 1)]
dasdas

            meeting_name  year location  ...  avg_hard_stint_by_driver  avg_med_stint_by_driver  avg_soft_stint_by_driver
0     Bahrain Grand Prix  2024   Sakhir  ...                      15.0                16.090909                      14.0
1     Bahrain Grand Prix  2023   Sakhir  ...                      15.0                16.090909                      14.0
1233  Bahrain Grand Prix  2025   Sakhir  ...                      15.0                16.090909                      14.0

[3 rows x 31 columns]

In [22]:
df.to_csv('prerace.csv')

In [31]:
# I will check the race_model as well

df_race = pd.read_csv('race_model.csv',index_col=0)
df_race.info()

<class 'pandas.core.frame.DataFrame'>
Index: 35748 entries, 0 to 35747
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   meeting_key              35748 non-null  int64
 1   meeting_name             35748 non-null  object
 2   year                     35748 non-null  int64
 3   location                 35748 non-null  object
 4   driver_number            35748 non-null  int64
 5   full_name                35687 non-null  object
 6   compound                 35748 non-null  object
 7   tyre_age                 35748 non-null  int64
 8   lap_number               35748 non-null  int64
 9   stint_number             35748 non-null  int64
 10  lap_duration             35748 non-null  float64
 11  fuel_corrected_duration  35748 non-null  float64
 12  avg_pit_time             35748 non-null  float64
 13  is_clean_lap             35748 non-null  bool
 14  safety_car               35748 non-null  int64
 15  yellow_flag              35748 non-null  int64
 16  red_flag                 35748 non-null  int64
 17  race_length_laps         35748 non-null  int64
 18  pit_out_lap              35748 non-null  bool
 19  lap_to_lap_change        35719 non-null  float64
 20  driver_pace_by_comp      35748 non-null  float64
 21  Avg_Deg_Rate             33860 non-null  float64
dtypes: bool(2), float64(6), int64(10), object(4)
memory usage: 5.8+ MB

In [42]:
df_na = df_race[(df_race['compound'].isin(['WET', 'INTERMEDIATE'])) & (df_race['Avg_Deg_Rate'].isna())]
df_na

       meeting_key       meeting_name  year  ... lap_to_lap_change  driver_pace_by_comp Avg_Deg_Rate
2789          1210  Monaco Grand Prix  2023  ...             0.000            98.184579          NaN
2790          1210  Monaco Grand Prix  2023  ...             0.000            98.184579          NaN
2791          1210  Monaco Grand Prix  2023  ...             0.000            98.184579          NaN
2792          1210  Monaco Grand Prix  2023  ...             0.000            98.184579          NaN
2793          1210  Monaco Grand Prix  2023  ...             0.000            98.184579          NaN
...            ...                ...   ...  ...               ...                  ...          ...
35400         1259   Miami Grand Prix  2025  ...             1.137           102.046667          NaN
35405         1259   Miami Grand Prix  2025  ...            -0.026           102.046667          NaN
35411         1259   Miami Grand Prix  2025  ...             0.301           102.046667          NaN
35417         1259   Miami Grand Prix  2025  ...             0.067           102.046667          NaN
35423         1259   Miami Grand Prix  2025  ...             0.490           102.046667          NaN

[1721 rows x 22 columns]

In [43]:
race_list = ['Bahrain Grand Prix', 'Saudi Arabian Grand Prix',
       'Australian Grand Prix', 'Azerbaijan Grand Prix',
       'Miami Grand Prix', 'Monaco Grand Prix', 'Spanish Grand Prix',
       'Canadian Grand Prix', 'Austrian Grand Prix', 'British Grand Prix',
       'Hungarian Grand Prix', 'Belgian Grand Prix', 'Dutch Grand Prix',
       'Italian Grand Prix', 'Singapore Grand Prix',
       'Japanese Grand Prix', 'Qatar Grand Prix',
       'United States Grand Prix', 'Mexico City Grand Prix',
       'São Paulo Grand Prix', 'Las Vegas Grand Prix',
       'Abu Dhabi Grand Prix', 'Chinese Grand Prix',
       'Emilia Romagna Grand Prix']


compounds= ['SOFT', 'MEDIUM', 'HARD']

# maybe a compound haven't been used in 
for comp in compounds:
    mask = df_race['compound'] == comp
    mean_deg = df_race.loc[mask, 'Avg_Deg_Rate'].mean()
    
    if pd.notna(mean_deg):
        df_race.loc[mask, 'Avg_Deg_Rate'] = (
            df_race.loc[mask, 'Avg_Deg_Rate'].fillna(mean_deg)
        )

df_race.info()

<class 'pandas.core.frame.DataFrame'>
Index: 35748 entries, 0 to 35747
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   meeting_key              35748 non-null  int64
 1   meeting_name             35748 non-null  object
 2   year                     35748 non-null  int64
 3   location                 35748 non-null  object
 4   driver_number            35748 non-null  int64
 5   full_name                35687 non-null  object
 6   compound                 35748 non-null  object
 7   tyre_age                 35748 non-null  int64
 8   lap_number               35748 non-null  int64
 9   stint_number             35748 non-null  int64
 10  lap_duration             35748 non-null  float64
 11  fuel_corrected_duration  35748 non-null  float64
 12  avg_pit_time             35748 non-null  float64
 13  is_clean_lap             35748 non-null  bool
 14  safety_car               35748 non-null  int64
 15  yellow_flag              35748 non-null  int64
 16  red_flag                 35748 non-null  int64
 17  race_length_laps         35748 non-null  int64
 18  pit_out_lap              35748 non-null  bool
 19  lap_to_lap_change        35719 non-null  float64
 20  driver_pace_by_comp      35748 non-null  float64
 21  Avg_Deg_Rate             34027 non-null  float64
dtypes: bool(2), float64(6), int64(10), object(4)
memory usage: 5.8+ MB

In [48]:
dasdas = df_race[(df_race['meeting_name'] == 'Bahrain Grand Prix') & (df_race['driver_number'] == 1)]
dasdas

       meeting_key        meeting_name  year  ... lap_to_lap_change  driver_pace_by_comp Avg_Deg_Rate
799           1141  Bahrain Grand Prix  2023  ...           -20.517            96.790667     0.099623
807           1141  Bahrain Grand Prix  2023  ...            -0.093            96.790667     0.099623
1252          1141  Bahrain Grand Prix  2023  ...            -0.772            98.671400     0.084486
11404         1229  Bahrain Grand Prix  2024  ...             0.330            98.671400     0.084486
11738         1229  Bahrain Grand Prix  2024  ...             0.312            96.790667     0.099623
34711         1257  Bahrain Grand Prix  2025  ...             0.498            98.671400     0.084486
34722         1257  Bahrain Grand Prix  2025  ...             0.681            98.671400     0.084486
34730         1257  Bahrain Grand Prix  2025  ...             3.056            98.671400     0.084486

[8 rows x 22 columns]

In [51]:
def add_missing_compounds(df):
    df = df.copy()

    compounds = {'SOFT', 'MEDIUM', 'HARD'}

    # Columns identifying a unique race and driver
    group_cols = ['meeting_name', 'driver_number', 'full_name']

    # Columns for which we want to calculate the mean
    mean_cols = ['driver_pace_by_comp', 'Avg_Deg_Rate']

    new_rows = []

    # Check each race-driver combination
    for _, group in df.groupby(group_cols, dropna=False):
        existing = set(group['compound'].dropna().unique())
        missing = compounds - existing

        for compound in missing:
            # Start from an existing row to preserve the schema
            row = group.iloc[0].copy()

            # Assign the missing compound
            row['compound'] = compound

            # Fill the two columns with their group means
            for col in mean_cols:
                row[col] = group[col].mean()

            new_rows.append(row)

    # Append all newly created rows
    if new_rows:
        df = pd.concat(
            [df, pd.DataFrame(new_rows)],
            ignore_index=True
        )

    return df

In [53]:
new_df = add_missing_compounds(df_race)
new_df

       meeting_key              meeting_name  year  ... lap_to_lap_change  driver_pace_by_comp Avg_Deg_Rate
0             1142  Saudi Arabian Grand Prix  2023  ...            -2.369            94.463200     0.005000
1             1142  Saudi Arabian Grand Prix  2023  ...            -0.277            96.204818     0.036663
2             1142  Saudi Arabian Grand Prix  2023  ...            -0.305            93.925758     0.005000
3             1142  Saudi Arabian Grand Prix  2023  ...            -0.062            93.981909     0.005000
4             1142  Saudi Arabian Grand Prix  2023  ...             0.180            96.204818     0.036663
...            ...                       ...   ...  ...               ...                  ...          ...
36284         1271  United States Grand Prix  2025  ...           -26.492            99.536667     0.024197
36285         1222  United States Grand Prix  2023  ...            -0.233           101.113431     0.015752
36286         1222  United States Grand Prix  2023  ...            -0.171           101.951488     0.011019
36287         1222  United States Grand Prix  2023  ...             0.197           101.541700     0.007633
36288         1271  United States Grand Prix  2025  ...             0.065           100.200543     0.024294

[36289 rows x 22 columns]

In [54]:
new_df.to_csv('racemodel.csv')